### ISSUE TITLE
Rails Generators y como nació Panacea

### ISSUE THREAD

**Issue by efigarolam** [MexicoOnRails/platicas#18]
[Panacea](https://www.panacea.website/) es una herramienta para agilizar la creación de aplicaciones de Rails e internamente utiliza una tecnología no tan conocida de Rails que son los generadores.

Me gustaría hablar de los Generadores de Rails y de los retos encontrados en el camino del desarrollo de Panacea.

**Comment by maxcodes** [comment]
Perfecto. Es una charla apta para principiantes o un poco más avanzada?

**Comment by efigarolam** [comment]
Pues creo que es un buen fit para desarrolladores con un nivel Intermedio. Trataré de hacerla lo más clara posible para que los Principiantes pues no pierdan el hilo.

**Comment by maxcodes** [comment]
Perfect. Te pregunto porque nos gusta siempre tener un balance entre charlas avanzadas y principiantes. Te late darla en enero? Sería el 8 de enero

**Comment by efigarolam** [comment]
Sí, todo bien con la fecha.

**Comment by maxcodes** [comment]
Listo, confirmado para enero 👍

**Comment by efigarolam** [comment]
Hola @maxcodes, oye me surgieron unos asuntos personales (me tengo que mudar antes del 15 de enero), crees que sea posible re-agendar mi plática para el meetup de Febrero?

**Comment by maxcodes** [comment]
Claro! Sin problemas :) 

Max Holzheu

**Comment by efigarolam** [comment]
Gracias.

**Comment by efigarolam** [comment]
Hola @maxcodes, ya tienen fecha para el meetup de Febrero? Quiero ir viendo la compra de mi vuelo

**Comment by maxcodes** [comment]
@efigarolam Segundo martes del mes es el 12! Qué alegre, te esperamos!

**Comment by efigarolam** [comment]
@maxcodes muchas gracias, allá los veo ;)

**Comment by maxcodes** [comment]
Links:
- https://www.panacea.website 
- https://github.com/panacea-rails/panacea 
- Presentación: https://mexicoonrails.slack.com/files/UD50PL02V/FG5BGSR40/rails_generators_-_panacea.pdf (tienes que ser [miembro del Slack](bit.ly/MexicoOnRailsSlack) para verla)
