### ISSUE TITLE
Running Ruby on Rails with Docker: Best practices and pitfalls

### ISSUE THREAD

**Issue by pabloxio** [MexicoOnRails/platicas#20]
Me gustaría compartir con ustedes la experiencia (y uno que otro truco) recopilada de varios años de ejecutar aplicaciones Ruby on Rails con Docker en AWS usando ECS, la charla iría más o menos así:
- ¿Qué es Docker? Un rápida intro y ejemplos sencillos. `Dockerfile`, `docker-compose.yml`.
- Dockerizando Ruby on Rails (Y en general cualquier app escrita en Ruby)
- Diferencias entre `development` y `production`

**Comment by maxcodes** [comment]
Super! Ya tuvimos una plática de Qué es Docker, pero estaría genial si la charla empieza más o menos a partir de "como hacer un Dockerfile que corra Rails", y de ahí pasarte a docker-compose, etc. 

Te late? Te agendamos para marzo. Avísame si te funciona!

**Comment by pabloxio** [comment]
Me parece mejor aún 👍

**Comment by maxcodes** [comment]
Super! Pues ya estás! Agendado para marzo 👍

**Comment by maxcodes** [comment]
En cuanto tengas, podrías ponernos por aquí el nombre de la charla?

**Comment by maxcodes** [comment]
Hola @pabloxco! Estamos para dentro de una semana verdad? Estoy muy emocionado por tu charla. Saludos!

**Comment by pabloxio** [comment]
Hola @maxcodes, ¡Claro que sí! En cuanto al título puede quedar así: `Best practices running Ruby on Rails with Docker` o `Running Ruby on Rails with Docker` o la original jaja
