### ISSUE TITLE
Cómo usar Brakeman para encontrar problemas de seguridad en tu app

### ISSUE THREAD

**Issue by maxcodes** [MexicoOnRails/platicas#9]
La seguridad de nuestras aplicaciones son responsabilidad de todos. Brakeman es una gema que te permite escanear tu código y encontrarte posibles problemas. Sería cool una charla explicando cómo usarla. 

Cualquier plática de seguridad en Rails es bienvenida, así que si tienes otra idea relacionada con seguridad, posteala como respuesta o como nueva issue y con gusto la consideramos 👍

**Comment by abuzzany** [comment]
Yo me apunto para esta!!!

**Comment by maxcodes** [comment]
Excelente! Vas para marzo, primera charla 👍  👍 

Yay, charla de Ángel!

**Comment by maxcodes** [comment]
En cuanto tengas, podrías ponernos por aquí el nombre de la charla?
